[package]
name = "rustsito"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
logbar = "0.1"
indicatif = "0.17.6"

[[bin]]
name = "rustsito"
path = "main.rs"
